layout: { rows: 6, columns: 4 }

layers:
  - name: "Default"
    bindings: [
      C_MUTE, C_PREV, C_NEXT, LT(1, C_PLAY_PAUSE),
      KP_NUMLOCK, KP_SLASH, KP_ASTERISK, KP_MINUS,
      KP_7, KP_8, KP_9, KP_PLUS,
      KP_4, KP_5, KP_6, &none,
      KP_1, KP_2, KP_3, &none,
      KP_0, KP_DOT, KP_ENTER, &none
    ]
    sensor_bindings:
      - behavior: &inc_dec_kp
        params: [ C_VOLUME_UP, C_VOLUME_DOWN ]

  - name: "Func"
    bindings: [
      &none, SYS_RESET, BOOTLOADER, &none,
      &none, QUESTION, PSCRN, UNDER,
      HOME, UP, PG_UP, EQUAL,
      LEFT, &none, RIGHT, &none,
      END, DOWN, PG_DN, &none,
      INS, DEL, KP_ENTER, &none
    ]
    sensor_bindings:
      - behavior: &inc_dec_kp
        params: [ C_BRI_UP, C_BRI_DOWN ]

boards:
  - name: "v1940"

shields:
  - name: "tidbit_numpad"

combos: []
macros: []
behaviors: []
